version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - VITE_HOST=${MY_HOST}
                - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        environment:
            - VITE_HOST=${MY_HOST}
            - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        depends_on:
            - backend
            - python-service
        networks:
            - app-network

    backend:
        build:
            context: ./lib
            dockerfile: Dockerfile
            args:
                - DB_HOST=parkathon-data
                - MY_HOST=${MY_HOST}
                - DB_USER=${DB_USER}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_NAME=${DB_NAME}
                - OPENAI_API_KEY=${OPENAI_API_KEY}
        environment:
            - DB_HOST=parkathon-data
            - MY_HOST=${MY_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        ports:
            - "9000:9000"
        depends_on:
            - parkathon-data
        networks:
            - app-network

    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
            - frontend
        networks:
            - app-network

    python-service:
        build:
            context: ./src
            dockerfile: Dockerfile
            args:
                - DB_HOST=parkathon-data
                - MY_HOST=${MY_HOST}
                - DB_USER=${DB_USER}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_NAME=${DB_NAME}
                - OPENAI_API_KEY=${OPENAI_API_KEY}
        environment:
            - DB_HOST=parkathon-data
            - MY_HOST=${MY_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        ports:
            - "9001:9001"
        depends_on:
            - parkathon-data
            - backend
        networks:
            - app-network

    parkathon-data:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
            - ./data/parkathon.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
